### PR TITLE
Attempting to fix false starts in overworld

### PR DESCRIPTION
**Pull request by MuteTiefling**
Due to https://github.com/EnigmaticaModpacks/Enigmatica9/issues/598 some players are starting in the Overworld. 

When this happens, the Twilight Forest is not even registered as a dimension, meaning nothing can be done to 'fix' them on first load. Therefore, we kick them with a message explaining the situation. 

Upon second load, they're teleported safely to the twilight using `TFPortalBlock`. 

Currently, however, once this is complete, the player cannot die... I suspect an issue with the worldspawn location but attempts to fix that via commands have so far failed.

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Dying issue may just be spawn protection? Attempted `/kill` again after writing this and it worked. Will keep testing.

**Comment by MuteTiefling** [comment]
Ok, after a few minutes I could take damage/die and succesfully respawn in Twilight Forest. Calling this a success.

**Comment by NielsPilgaard** [comment]
Hmm, this would also trigger for players who have already made it to the overworld, not just first launches.

**Comment by MuteTiefling** [comment]
Oh right. I'll add a check for that.

**Comment by NielsPilgaard** [comment]
If you also check the starting items game tag to see if it really is first launch, this would work well. We'd have to set a priority on each script though, so this one runs before starting items.

**Comment by MuteTiefling** [comment]
Alright, that ought to do it

**Review by NielsPilgaard — CHANGES_REQUESTED** [review]
Starting Errors must run before Starting Items, otherwise starting errors will never trigger.
(The highest priority number is run first)

**Comment by MuteTiefling** [comment]
Ah dang. Alright I won't be able to swap it for a bit still if you want to do a release.

**Comment by NielsPilgaard** [comment]
No worries I'll do it 👍

**Review by NielsPilgaard — APPROVED** [review]

**Pull request merged**
