### PR TITLE
AE2 Quests and more

### PR DESCRIPTION
**Pull request by MuteTiefling**
Implements quests and rewards for AE2. 

Re-organizes existing quests.

Cleans up building, storage, redstone/logic quests and unhides those that were hidden.

### CODE REVIEW

**Comment by MuteTiefling** [comment]
AE2 stuff in particular could use a proof read to be sure I haven't misrepresented anything.

**Comment by MuteTiefling** [comment]
Also introducing an in-world conversion for AE2 Crafting CPUs.

Recipes look like this: 
image

By Right Clicking any of the Crafting CPU blocks with the appropriate item, they're converted to the equivalent block like these shapeless recipes
image

Normally one would need to pick up the block, sneak right-click it to get the component and crafting unit blocks refunded, then re-craft them, and re-place them. Instead this in-world recipe lets you skip the pickup and replace while still consuming/refunding the appropriate items.

**Comment by MuteTiefling** [comment]
Also rebalancing skeletons. They're maybe a little too deadly.

Reduces spawn rates of skeletons with tipped arrows. Makes blasting arrows the most rare. Guaranteed to drop 5x of whatever arrow they have.

Made similar adjustments to pillagers.

**Review by NielsPilgaard — APPROVED** [review]
I'd like to get this merged into dev to review quests in-game, I've reviewed all the rest and it look solid. Slightly confused about the new lychee ae2 recipes, but I'm sure it'll be easier to understand for me in-game 😄

**Pull request merged**
