### PR TITLE
Delete tweaks_ultimine.json

### PR DESCRIPTION
**Pull request by Kanzaji**
We don't have Ultimine ^^"

I should probably write something else, llike about using hamers etc other mods provide, but I don't exactly have time now, and I'm sure we would forget about this entry again 😅

### CODE REVIEW

**Comment by Darkere** [comment]
has issues

**Comment by Darkere** [comment]
in case you didn't notice the retarget has added another commit to this :D

**Comment by Kanzaji** [comment]
Ah this commit ^^" Its from Master branch, I kinda can't do anything about it.

**Review by NielsPilgaard — APPROVED** [review]
I should've merged master into develop earlier anyway :P thanks!

**Pull request merged**
