### PR TITLE
Expert recipes

### PR DESCRIPTION
**Pull request by MuteTiefling**
Retexture and recipe update for Sacrificial bowls
The previous recipe, using Compressed Stone, was too late for the intended purpose (very early game occultism rituals) so I've moved it earlier and updated the texture to match the recipe. These are now craftable immediately after killing the Naga (need to obtain Archwood from it)
image
image

Textures:
image
image

## Storage

Ars Storage kinda came out of left field with respect to our plans for early game storage. AE2 will remain super early still, but that does require power and that's a little bit of effort to obtain.

So Ars Storage fills the super early game role. 
Update Dominion Wand to be craftable early game
image

Repository 
image

Storage Lectern
image

Bookwyrms for operating the storage
image

Ritual Brazier moved to Chapter 2
image

## Power
Upon further consideration, I think won't feel very nice to build an Aura Forge as starting FE generation, so I'm re-working the Dim Pulsating Crystal to be the entry point now. 

Dim Arcanite Crystal (Texture WIP)
image
image

Dim Pulsating Crystal
image

## Brooms
Brooms are now unbreakable. Removed sacrifice criteria from the craft and tied it to the other 'Familiar' crafts by adding Mindful Trance Blend to the craft. All Familiars use this so it's an easy searchable item to find them in JEI. Quests mention this too. 

image

## Quests
Chapter 1 reworked to account for recent changes. Layout improved towards a more final layout instead of just a flow chart

Chapter 2 quests fleshed out more

## Nether Stars
Still drop from the Wither, but to avoid repeating the gateway for more stars, they can instead be condensed from Ether Gas
image
image

The Blast Chiller gives the highest yield for now as it is slated to be later in progression. 

## Gem Based Equipment
This is all enchantment crafting now, so all Diamond armor/tools as well as all blue skies equipment is made on the enchanting apparatus. This keeps the NBT from the source equipment (gold in all cases) and transfers it to the new equipment
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
# Tech

**Comment by MuteTiefling** [comment]
# Magic

**Comment by MuteTiefling** [comment]
Happier with Chapter 2 at this point. Will call this good here and move on to more in another PR

**Comment by MuteTiefling** [comment]
# Chapter 3
Getting a start on this, at least the end of it.
The player will need to defeat a Warden to obtain a Sculk Catalyst. This can be used to create a Sculk farm by killing mobs near the Catalyst so it can convert blocks to Sculk.

With Sculk, they can create Echo Shards
image

Which can in turn be converted to Pandemonium (renamed Polonium)
image

And converted into Aetherium (renamed antimatter) in an SPS
image

**Comment by MuteTiefling** [comment]
## Processor Re-Introduction
Circuits and Processors renamed
image
image

Runic Manifolds start in the Bottling Machine
image

Extra recipe introduced for faster Liquefied Source conversion
image
As well as extra ways of forming the gems
image

Each tier of manifold involves some runes and some purified ink
image

These are then engraved via spirits
image

Update Machine Frames
image
image


and PCBs
image

**Comment by MuteTiefling** [comment]
## AE2 Extras
Bunch of misc stuff I hadn't appropriately placed yet
Biometric Card
image
Memory Card
image

Network Tool
image

Entropy Manipulator
image

ME Wireless Access Point
image

Wireless Receiver
image

Spatial Components
image
image
image

ME Chest
image

Spatial Anchor
image

Spatial IO Port
image

Energy Cells
image
image

Quantum Link Chamber
image

Quantum Ring
image

Security Terminal
image

Cell Workbench
image

**Comment by MuteTiefling** [comment]
Done for realsies for now >.>

**Review by NielsPilgaard — APPROVED** [review]
Looks good to me :D

**Pull request merged**
