### PR TITLE
Thermal integration and quest updates

### PR DESCRIPTION
**Pull request by MuteTiefling**
Updates Thermal quest line, expanding it and offering better explanations
Adds thermal to sawing and crushing scripts for trees/dyes. 
Adds an alternate route to Fluix crystals through Thermal.
Rebalance dynamos lightly, giving incentive to try some of the more interesting ones. 
Reduces max level of Holding to be only slightly higher than Thermal's default. 

Todo:
- [x] Finish quests
- [x] Update quest loot tables to include some of the new fun things that have been added
- [x] Add plants to the Phytogenic insolator
- [x] Add Thermal's plants to the plant registry
- [x] Attempt to unify Thermal/PNC/IE fuels and oil
- [x] Add fertilizers to Thermal machines

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Think I'll work on the igneous extruder at a later time. need to think how I want to do it and what to include.

**Comment by MuteTiefling** [comment]
Attempted to resolve the following error in reading the 'type' of Creeper Overhaul creepers, but the fix causes the script to crash on load (works after reload, however). 

I fear Creeper Overhaul is doing something weird here as there should be no reason for this to happen. Could find no clean way of detecting these guys to skip them in the script. 

https://gist.github.com/MuteTiefling/1f883522c0c028b45daf40e8b88bea0e

**Comment by katsutosh** [comment]
> I fear Creeper Overhaul is doing something weird here as there should be no reason for this to happen. Could find no clean way of detecting these guys to skip them in the script.

Here is a way of detecting creeperoverhaul creepers. (tested it with the jungle creeper)
You can get the `entityType` of the entity. The return is `entity.creeperoverhaul.jungle_creeper` as type object.
Convert the object into a string and check if the string includes `creeperoverhaul`

```
String(event.entity.entityType).includes('creeperoverhaul')
```

**Comment by MuteTiefling** [comment]
That does appear to do it, thank you kindly!

**Review by NielsPilgaard — APPROVED** [review]
Very nice!

**Pull request merged**
