### PR TITLE
E9E continued feedback

### PR DESCRIPTION
**Pull request by MuteTiefling**
- Abyssaline made into a much more powerful fuel given how much work it takes. 
- RLC changed, minorly gated now
image
- Oil is no longer bottomless in Expert
- Twilight Forest Chests may now be crafted directly, no vanilla chest required. 
- ClientTweaks Autoclimb disabled.
- Shears renamed/retextured to Botanist's Shears, recipe moved forward:
image
- Allays may now be summoned
image

### CODE REVIEW

**Comment by iarspider** [comment]
> Oil is no longer bottomless in Expert

But... why? Just for the sake of hardcore-ness?

**Comment by MuteTiefling** [comment]
Because I don't want it available for free from Create.

It's still accessible via the IF laser drill.

**Comment by iarspider** [comment]
But you still need to get 10k buckets of oil to make it infinite... Ah, "free" is "without upkeep", I guess (i.e. only initial investment)

**Comment by MuteTiefling** [comment]
Thanks for your feedback. If it's actually problematic during the course of play, I'll reconsider.

**Pull request merged**
