### PR TITLE
Disable poorly designed negative aura features

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
Any effect that can be triggered by accident that requires restoring the world from a backup is not well designed.  

These features ensure that once triggered, there is virtually no way to correct them and the only course of action is to restore the world from a backup as the area will either become leveled entirely (via explosion) or uninhabitable (via breathless).

The only case where it is even possible to do something is if the event occurs while a player is actively in the region, and the player has the necessary knowledge to understand _why_ the issue is happening and how to restore the aura levels.  

If a player is not nearby and returns to the aura drained, there is no course of action except restoring a backup (as Breathless III is unlivable, and explosions will likely have flattened the region entirely after some time has passed).

### CODE REVIEW

**Comment by MuteTiefling** [comment]
So, out of curiosity, what are the sources of the problem for you? As of 1.13 power crystals should no longer drain aura into unsafe levels. That was most likely the leading cause of issues as people 

That leaves extraneous fire starters and the tree of life as potentially problematic. The former because its likely to be used in automation, and the latter because some people are somehow having higher aura drain from the lamp of sanctuary than the tree produces. 

Probably the water source too if it's being used extensively. 

As an aside, from an admin perspective you can correct the aura via commands. No need to restore the whole server. The player will just have to clean up broken blocks. 

I'm not opposed to removing the explosions, but I do feel there should be some consequences. Otherwise these things that can run into negative can be used endlessly without generating aura.

**Comment by Shadows-of-Fire** [comment]
I believe the issue in this case was a Soul Cage from spirit that was left running, though I'm not 100% certain (nor is the player in question).  

I came back to an area totally leveled to bedrock by explosions, so "clean up the broken blocks" is... not a solution there.

Breathless is less horrible, more just annoying, but you can't exactly go "fix" breathless if all your items are trapped in a Breathless region, so you're SOL there as well.

Aside, I'm a bit more annoyed at it than usual because configswapper made it impossible to disable until I figured out that CS was a thing that existed and was constantly overriding the main file. Trying not to weigh that heavily in this analysis though.

**Comment by MuteTiefling** [comment]
I think we'll go with just the explosions for now and see where that goes. 
https://github.com/EnigmaticaModpacks/Enigmatica9/pull/748

**Comment by NielsPilgaard** [comment]
*Without explosions :P

**Comment by MuteTiefling** [comment]
go with *just disabling* explosins, I meant to say :D

**Pull request closed without merging**
