### PR TITLE
Expert Tuning

### PR DESCRIPTION
**Pull request by MuteTiefling**
# Misc

## Mekanism

Meka Suit made easier to craft since power requirements are more limiting. This is very good armor on its own, but I expect the shields will be tough to power early on. 

It's roughly on par with PNC armor, in terms of craft difficulty. 

Disabled Modules: 
- Everything related to Radiation (since radiation is similarly disabled)
- Inhalation Purification. I wanted to keep this, but it removes *all* potion effects, even those we grant by wearing the set to balance it. Seems there's no easy fix for this until 1.20.

Armor pieces:
image
image

Set comes with the color module pre-installed and pre-set to a dark grey. 

Glyph of Mana Bubble
image

Mekasuit and Mekatool modules
Changed to use Aluminum and Osmium instead of plastic. Most follow a similar pattern still with a few exceptions
image

Creative Flight, for instance, takes a little more effort since it's the best/fastest in the game
image

Modification Station
image

## Create
Copycat blocks moved to ironwood
image

Likewise for Brass fittings (renamed to Fancy)
image

Rose Quartz Lamps
image

Elevator Pulley
image

## Arcanite Crystals
Changed again. Each craft now yields more. 
Full chain:
image
image
image

Sylvanite now uses Lithium instead of Silver
image

Brooms updated. All starter tiers work as before. Just adding recipes for the new types. 
image

Mahogany (faster) is gated a little closer to the end of chapter 1
image

Brushes
Regular brushes are no longer unbreakable. 
Ars Scalaes has a Magebloom Brush that is effectively unbreakable if the player has enough of a mana pool (doesn't take much). 
image

Hexerei also introduces a new type of brush which is faster than the others. This has been made unbreakable
image

Moon Dust
This will only craft under the light of a full moon. With this recipe, automating it would be as simple as hoppering in Silver Dust and letting it be. But I don't expect Moon Dust to become a heavy requirement regardless. 
image

Moon Dust has also been added to a few other crafts
The refinery needs it now for Quick Silver. This is a catalyst, and isn't used up. So they won't need a ton of it.
image

It's also used for Threads to upgrade Ars Armor. Again, not something they'll need a lot of. 
image

And required for the first bit of Sky Stone Dust until they can upgrade to other methods. 
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
# Tech

**Comment by MuteTiefling** [comment]
# Magic

**Comment by MuteTiefling** [comment]
# Progression

**Comment by NielsPilgaard** [comment]
Should I wait a bit before reviewing? 😄

**Comment by MuteTiefling** [comment]
Hah, no go ahead. I'll stop now :D 

Just had a couple ideas pop into my head is all

**Review by NielsPilgaard — APPROVED** [review]

**Pull request merged**
