### PR TITLE
Remove refinery recipe overwrite

### PR DESCRIPTION
**Pull request by DAmNRelentless**
This pull request removes the custom recipe for biodiesel in the IE refinery.
Since it's equivalent to the default recipe, I don't know what exactly this was for but maybe it was an approach to fix the unification of the catalyst.

With the new Almost Unified update, we will take care of catalysts as well as crusher secondary outputs. The required Almost Unified version will be `v0.4.2` once it's released.

When Kanz reported these issues to us and told me he isn't available until wednesday, I tested it myself. As there were issues on a dedicated server before, I made sure to test it on there as well. The crusher secondaries worked fine but I was very confused when the refinery catalysts didn't and then realized there is this script which overrides the unified recipe as the KJS recipe event runs after the unification.

I will release the new AU update within the next hour so this should hopefully get rid of all issues once you update the mod.

### CODE REVIEW

**Comment by DAmNRelentless** [comment]
Another little note. There is `forge:dusts/potassium_nitrate` in the AU tag ownerships with the owner being `forge:dusts/niter`. As far as I can tell, a tag like that doesn't exist.

**Comment by DAmNRelentless** [comment]
Accidentally hit close, wonderful.

**Comment by NielsPilgaard** [comment]
Thanks for the PR! File deletion in modpacks doesn't really work unfortunately, so we usually replace the contents of the file we want to delete with `// TODO: Delete in next breaking change.` - Would you mind changing this PR to do that instead?


> Another little note. There is `forge:dusts/potassium_nitrate` in the AU tag ownerships with the owner being `forge:dusts/niter`. As far as I can tell, a tag like that doesn't exist.

Nice catch - Would you like to address it, or should I go ahead? :)

**Comment by DAmNRelentless** [comment]
Completely forgot about this, you are right. Just fixed it.
Also just pushed our release tags so the AU update should be available within the next minutes.

> Edit: I'm not sure how to fix it actually :P

It only requires the removal of `"forge:dusts/potassium_nitrate"` from the `"forge:dusts/niter"` entry inside the `unify.json` config. But I didn't do it yet because I am not sure why it's in there and there may be plans to add new materials with that tag. Although that would be quite useless if it's unified to the owner tag anyways. 😄

**Comment by MuteTiefling** [comment]
There's no reason to delete the whole script :D And this is also unifying the fluid output, so I'd rather just update the catalyst to be the correct item. 

To avoid it looking like an AU change, we can just remove the ID and make a new recipe ID

**Comment by DAmNRelentless** [comment]
I see. I could do the catalyst change myself but I am not sure what recipe ID you want so I leave that up to you. If you don't use the original ID, you might need to remove the original one too and I don't know if you have logic for that in place already. 😄

**Pull request closed without merging**
