### PR TITLE
Probably a real tag fix

### PR DESCRIPTION
**Pull request by MuteTiefling**
So, after making this change and testing for a good... twenty or so reloads without error, I've come to the conclusion that the real issue with tag scripts failing is if any variables are defined withing the tag script... 

This removes all of those variables and things appear to be running much more smoothly. I hate it, but it works.

### CODE REVIEW

**Comment by MaxNeedsSnacks** [comment]
Shouldn’t this be reported to Lat so he can try to find a fix? 😅

**Comment by Kanzaji** [comment]
Time to fix my scripts on EE-Setup now 😅

**Comment by MuteTiefling** [comment]
> Shouldn’t this be reported to Lat so he can try to find a fix? 😅

The response from lat when I reported it was that he'd try to remember to look into it.

**Comment by Kanzaji** [comment]
Are we talking about that thread on latcord I've made ^^"? We got to the conclusion about loops in tag scripts being the problem, so I'm fairly sure lat doesn't know about issue of variables :P (Or I had missed something / you asked him somewhere else 😅)

**Comment by MuteTiefling** [comment]
Yes, and at the time we thought it might be loops but weren't completely sure.

**Comment by MuteTiefling** [comment]
Well, so much for a real fix....

https://gist.github.com/MuteTiefling/47590084c273f7d2f996b87148f30f5e

And on top of it, tags for recipes don't exist before recipe scripts fire on first load. 

```js
ServerEvents.recipes((event) => {
    const id_prefix = 'enigmatica:base/dye_crushing/';

    colors.forEach((color) => {
        ['large', 'small'].forEach((input_size) => {
            let input = `#enigmatica:${input_size}_dye_sources/${color}`;

            console.log(String(getItemsInTag(input)));
            if (getItemsInTag(input).includes('minecraft:barrier')) {
                console.log('yeet');
                return;
            }
```
logging out the contents of the dye tags on first load and they're all empty. Naturally this works after a reload...

**Pull request merged**
