### PR TITLE
Make theoneprobe not require a probe

### PR DESCRIPTION
**Pull request by Gcat101**
Title.

### CODE REVIEW

**Comment by MuteTiefling** [comment]
It's already disabled in our configs though?

**Comment by MuteTiefling** [comment]
Oh lol this is 9! That is going to take some getting used to.

**Comment by Gcat101** [comment]
also disabled the "theoneprobe readme" spawning at the start

**Review by NielsPilgaard — APPROVED** [review]

**Comment by NielsPilgaard** [comment]
Thanks!

**Pull request merged**
